### ISSUE TITLE
too strict

### ISSUE THREAD

**Issue by kimstik** [ludwig-austermann/gcodeplot#5]
I have issue with following code:
```
G00 X 58.9748 Y 118.0934
G01 X 61.9683 Y 107.8599
```

You don't seem to accept spaces after X/Y and differentiate between G0 and G00

**Comment by ludwig-austermann** [comment]
The spaces have not been a problem with v0.3 (you can also append `\t`).
In v0.4, `G0` (nonlinear move) has been added as an instruction and the possibility to write `G0` as `G00` and similar.

**Comment by kimstik** [comment]
I guess that leading zeros and all spaces should be ignored.
following code looks strange but correct:
`G 000 0 X58.97 48 Y11 8.09 34`

**Comment by ludwig-austermann** [comment]
Can you explain to me why such relaxed grammar should be preferable? It is very hard to understand your given code, and I think that no human and no code would output such code.

That having said, numbers are already allowed to have leading (and trailing (after the decimal separator)) zeros. For example, one can write:
```text
G0    X 0040.400   Y    2.1e5
  G1  X 0001.000   Y    1e-2
```

Only the instruction term does not allow for added whitespace nor leading zeros.

**Comment by kimstik** [comment]
That the question. Generally g-code not require whitespace at all.
"Spaces and tabs are allowed anywhere on a line of code and do not change the meaning of the line, except inside comments. This makes some strange-looking input legal. The line G0X +0. 12 34Y 7 is equivalent to G0 x+0.1234 Y7, for example."
https://linuxcnc.org/docs/html/gcode/overview.html

I saw once postprocessor which generate G000 and G001 :) why not?

**Comment by kimstik** [comment]
> G0    X 0040.400   Y    2.1e5
>   G1  X 0001.000   Y    1e-2

funny. I newer saw scientific notation in gcode.
Do you have some references?

**Comment by ludwig-austermann** [comment]
No not, I guess there would be no problem with removing scientific notation in the parser.
Allowing `G0...0{Instruction Number}` should also be no issue.

> The line G0X +0. 12 34Y 7 is equivalent to G0 x+0.1234 Y7, for example.

But I somehow do not want to contribute to writing ugly code if there is no reason to.
